name       : python-pyliblo
version    : 0.10.0
release    : 6
source     :
    - https://github.com/dsacre/pyliblo/archive/0.10.0.tar.gz : 2013fe90e84bbb5bfb81d382f56e974442fd84fa7931c9986d19c5338c6b9883
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python wrapper for the liblo OSC library
description: |
    Pyliblo is a python wrapper for the liblo OSC library.
builddeps  :
    - pkgconfig(liblo)
    - cython
rundeps    :
    - liblo
build      : |
    %python3_setup
install    : |
    %python3_install
